### ISSUE TITLE
Portable version?

### ISSUE THREAD

**Issue by Lacyway** [WaGi-Coding/mordhau-rcon-tool#1]
Hey,

Love the tool. Any chance of making a portable version that needs no installing? Thanks!

**Comment by WaGi-Coding** [comment]
Hey, i wanted to make it portable first, but unfortunately when i merge the needed dlls into my exe with ILMerge, the UI get's fckd up for some reason, so i've decided to make an installer instead. You can however compile it yourself and just put the needed dlls into the same folder as the exe.

**Comment by Lacyway** [comment]
Thank you, I appreciate the quick response.
