### ISSUE TITLE
keep getting an error

### ISSUE THREAD

**Issue by BallisticOK** [WaGi-Coding/mordhau-rcon-tool#2]
hello when ever i try to use your tool i get 

Connecting...
Error: Connection closed by remote host

but it will connect on any other RCON tool 
i like the look of yours more then some others if you can help plz do 

EDIT:

it works with a minecraft server but not my FiveM server

**Comment by WaGi-Coding** [comment]
Hey, this tool was mostly made for the game mordhau, it should work pretty well with other games in it's current state, but it will implement game specific formatting, features, etc. in the future. Not sure what could be the problem in this case. Maybe another way auf authentificating, which generic rcon tools may support, no clue tbh. However let me know if you have problems with mordhau specifically, not sure if thats the case here?!

Greetings
